### ISSUE TITLE
Few entries missing author and title.

### ISSUE THREAD

**Issue by hashes4merkle** [hashes4merkle/doppelgaenger-detection#2]
Screenshots pasted below.

<img width="1535" alt="Screen Shot 2020-11-15 at 4 39 34 PM" src="https://user-images.githubusercontent.com/5827364/99189416-5bc6d380-2761-11eb-87e4-f134bf2b8e09.png">

<img width="1514" alt="Screen Shot 2020-11-15 at 4 39 12 PM" src="https://user-images.githubusercontent.com/5827364/99189421-61241e00-2761-11eb-8b67-90628f0a78c0.png">

**Comment by leonwolter** [comment]
mostly fixed by now. there are still some entries missing the author but most of those articles don't even have an author.
